spring:
  application:
    name: ms-cliente-persona
    # Spring Data
    ## Datasource configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cliente_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  ## RabbitMq configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        threads:
          virtual:
            enabled: true
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
## Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

## Swagger configuration
swagger:
  base:
    package: com.devsu.ing.deiberv.ms.cliente
  project:
    name: ${spring.application.name}
    description: Api MS Cliente
    version: 1.0
    contactName: Deiber Velandria
    contactEmail: deiberv@gmail.com

## Custom RabbitMQ configuration
rabbitmq:
  queue-name: cliente_queue
  exchange-name: cliente_exchange
  routing-key: cliente_routing_key

